class YouTrackException(Exception):
    message: str = ...

    def __init__(self, message: str) -> None: ...


class UnauthorizedYouTrackException(YouTrackException): ...


class ForbiddenYouTrackException(YouTrackException): ...


class NotFoundYouTrackException(YouTrackException): ...
